name: ${COMPOSE_PROJECT_NAME:-gbox}

services:
  api-server:
    container_name: ${CONTAINER_NAME:-gbox-api-server}
    build:
      context: ../../packages/api-server
      dockerfile: ../../packages/api-server/Dockerfile
    image: babelcloud/gbox-api-server:${API_SERVER_IMG_TAG:-latest}
    ports:
      - "${SERVICE_PORT:-28080}:${SERVICE_PORT:-28080}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GBOX_HOME:-$HOME/.gbox}:/var/gbox
    environment:
      - TZ=Asia/Shanghai
      - GBOX_HOST_SHARE=${GBOX_SHARE:-$HOME/.gbox/share}
      - GBOX_SHARE=/var/gbox/share
      - GBOX_NAMESPACE=${GBOX_LABEL:-gbox-boxes}
      - PORT=${SERVICE_PORT:-28080}
    restart: unless-stopped 