name: ${PREFIX}${PREFIX:+-}gbox

services:
  api-server:
    container_name: ${PREFIX}${PREFIX:+-}gbox-api-server
    build:
      context: ../../packages/api-server
      dockerfile: ../../packages/api-server/Dockerfile
    image: babelcloud/gbox-api-server:${API_SERVER_IMG_TAG:-latest}
    ports:
      - "${SERVICE_PORT:-28080}:28080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GBOX_HOME:-$HOME/.gbox}:/var/gbox
    environment:
      - TZ=Asia/Shanghai
      - GBOX_BROWSER_HOST=${GBOX_BROWSER_HOST:-host.docker.internal}
      - GBOX_HOST_SHARE=${GBOX_SHARE:-$HOME/.gbox/share}
      - GBOX_SHARE=/var/gbox/share
      - GBOX_NAMESPACE=${PREFIX}${PREFIX:+-}gbox-boxes
      - PY_IMG_TAG=${PY_IMG_TAG:-latest}
      - TS_IMG_TAG=${TS_IMG_TAG:-latest}
      - SH_IMG_TAG=${SH_IMG_TAG:-latest}
    restart: unless-stopped
    
  mcp-server:
    container_name: ${PREFIX}${PREFIX:+-}gbox-mcp-server
    build:
      context: ../../packages/mcp-server
      dockerfile: ../../packages/mcp-server/Dockerfile
    image: babelcloud/gbox-mcp-server:${MCP_SERVER_IMG_TAG:-latest}
    ports:
      - "${MCP_SERVICE_PORT:-28090}:28090"
    volumes:
      - ${GBOX_HOME:-$HOME/.gbox}:/var/gbox
    environment:
      - TZ=Asia/Shanghai
      - API_SERVER_URL=${MCP_API_SERVER_URL:-http://api-server:28080/api/v1}
    restart: unless-stopped 