name: gbox-test

services:
  api-server:
    container_name: gbox-api-server-test
    build:
      context: ../../packages/api-server
      dockerfile: ../../packages/api-server/Dockerfile
    image: babelcloud/gbox-api-server:${API_SERVER_IMG_TAG:-latest}
    ports:
      - "28081:28081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GBOX_HOME:-$HOME/.gbox}:/var/gbox
    environment:
      - TZ=Asia/Shanghai
      - GBOX_HOST_SHARE=${GBOX_SHARE:-$HOME/.gbox/share}
      - GBOX_SHARE=/var/gbox/share
      - GBOX_LABEL_COMPOSE=gbox-boxes-test
      - PORT=28081
    restart: unless-stopped 