# Server configuration
server:
  port: 28080

# Application configuration
gbox:
  # Base directories
  home: "${HOME}/.gbox" # Base directory for all application data
  share: "${gbox.home}/share" # Directory for shared files
  host_share: "${gbox.share}" # Directory for shared files on host

# Cluster configuration
cluster:
  mode: docker # Possible values: docker, k8s

  # Docker specific settings
  docker:
    host: "" # If empty, will try default socket paths

  # Kubernetes specific settings
  k8s:
    cfg: "" # If empty, will try default paths
