# Server configuration
server:
  port: 28080

browser:
  host: "localhost"

# File service configuration
file:
  # Base directories
  home: "${HOME}/.gbox" # Base directory for all application data
  share: "${file.home}/share" # Directory for shared files
  host_share: "${file.share}" # Directory for shared files on host

# Cluster configuration
cluster:
  mode: docker # Possible values: docker, k8s
  namespace: gbox-boxes

  # Docker specific settings
  docker:
    host: "" # If empty, will try default socket paths

  # Kubernetes specific settings
  k8s:
    cfg: "" # If empty, will try default paths
