#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ def extraMounts():
- hostPath: #@ data.values.home + "/.gbox/workspace"
  containerPath: /workspace
#@ end

#@ def kubeadmConfigPatches():
- |
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  ---
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  serverTLSBootstrap: true
#@ end

#@ def extraPortMappings():
#@ end

#@ def node(role, extraPorts=False):
- role: #@ role
  kubeadmConfigPatches: #@ kubeadmConfigPatches()
  extraMounts: #@ extraMounts()
  #@ if extraPorts:
  extraPortMappings: #@ extraPortMappings()
  #@ end
#@ end

---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gbox
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: #@ data.values.apiServerPort
nodes: #@ node("control-plane", extraPorts=False)

