name: Build Sandbox Images

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:

  build-api-server:
    uses: ./.github/workflows/build-gbox-image.yml
    with:
      build_default_branch_manifest: true
      timeout_minutes: 30
      image_name: gbox-api-server
      build_context: ./packages/api-server
      file: ./packages/api-server/Dockerfile
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-python:
    uses: ./.github/workflows/build-gbox-image.yml
    with:
      build_default_branch_manifest: true
      timeout_minutes: 30
      image_name: gbox-python
      build_context: ./images/python
      file: ./images/python/Dockerfile
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-typescript:
    uses: ./.github/workflows/build-gbox-image.yml
    with:
      build_default_branch_manifest: true
      timeout_minutes: 30
      image_name: gbox-typescript
      build_context: ./images/typescript
      file: ./images/typescript/Dockerfile
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}