name: Builds

on:
  push:
    branches: [ "**" ]
    paths:
      - 'packages/cli/**'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'packages/cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: packages/cli/go.sum

      - name: Install dependencies
        run: |
          cd packages/cli
          go mod tidy

      - name: Run unit tests
        run: |
          cd packages/cli
          make test

      - name: Install expect for e2e tests
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Set up Python for e2e tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python dependencies for e2e tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install playwright==1.55.0

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Run e2e tests
        run: |
          cd packages/cli
          make e2e
        env:
          GBOX_API_KEY: ${{ secrets.GBOX_API_KEY }}
          GBOX_BASE_URL: ${{ secrets.GBOX_BASE_URL }}
          CI: true



